spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.129/sellbak?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.0.129
    port: 6379
server:
  context-path: /sell
  port: 8080
wechat:
  mpAppId: wxd898fcb01713c658
  mpAppScret: 01d65e5f44d6e2d777996dc60e94ea58
  openAppId: 123455
  openAppScret: 123124
  mchId: 1483469312
  mchKey: C5245D70627C1F8E9964D494B0735025
  keyPath: D:/ngrok/h5.p12
  notifyUrl: http://merryyou.mynatapp.cc/sell/pay/notify
  templateId:
    orderStatus: 12344

projectUrl:
  wechatMpAuthorize: http://merryyou.mynatapp.cc
  wechatOpenAuthorize: http://merryyou.mynatapp.cc
  sell: http://merryyou.mynatapp.cc

#mybatis:
#  mapper-locations:


#apache ab
#ab -n 100 -c 100 http://www.baidu.com    -n 100 请求  -c 100 人  -c 60秒
#ab -t 60 -c 100 http://www.baidu.com  60秒内100个人请求
