spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.129/sellbak?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  context-path: /sell
  port: 8080
wechat:
  mpAppId: wxb962cbf908779e5e
  mpAppScret: 01d65e5f44d6e2d777996dc60e94ea58

#mybatis:
#  mapper-locations:


#apache ab
#ab -n 100 -c 100 http://www.baidu.com    -n 100 请求  -c 100 人  -c 60秒
#ab -t 60 -c 100 http://www.baidu.com  60秒内100个人请求
